apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "Initial release (v1) with nginx 1.25"   
spec:
  replicas: 3
  revisionHistoryLimit: 10             # Old ReplicaSets kept for rollback (default: 10)
  minReadySeconds: 5                   # Seconds Pod must be Ready before counted Available (default: 0)
  progressDeadlineSeconds: 300         # Mark rollout stalled after N seconds (default: 600)
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1          # allow 1 extra pod during update. Default is 25%
      maxUnavailable: 0    # keep all existing pods available. Default is 25%
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.25